---
- hosts: "all"
  vars_files:
    - ~/ansible/vars.yml
  become: true
  tasks:
  - name: Update and upgrade
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  - name: install wireguard
    ansible.builtin.apt:
      name: "wireguard"
      state: "latest"
  - name: Do forwarding
    shell: echo 'net.ipv4.ip_forward=1' > /etc/sysctl.conf 
  - name: Apply forwarding 
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
  - name: copy configuration
    copy:
      src: ~/ansible/wg0.conf
      dest: /etc/wireguard
      owner: kami
      group: kami
      mode: '0777'
  - name: enable wireguard
    ansible.builtin.systemd:
      name: wg-quick@wg0.service
      enabled: yes
  - name: start wireguard
    ansible.builtin.systemd:
      name: wg-quick@wg0.service
      state: started