---
- hosts: "all"
  become: true
  tasks:
  - name: include vaulted varibles
    include_vars: ~/ansible/vars.yml
  - name: install wireguard
    ansible.builtin.apt:
      name: "wireguard"
      state: "latest"
      update_cache: true
      